export const EMOTION_WORD_MAP: Record<
  string,
  Record<string, string[]>
> = {
  Happy: {
    A: ['Amazing', 'Abundant', 'Accepting', 'Accomplished'],
    B: ['Brilliant', 'Beautiful', 'Blessed', 'Blissful'],
    C: ['Cheerful', 'Charming', 'Confident', 'Creative'],
    D: ['Delighted', 'Dazzling', 'Daring', 'Divine'],
    E: ['Excited', 'Ecstatic', 'Elegant', 'Energetic'],
    F: ['Fantastic', 'Fabulous', 'Fearless', 'Friendly'],
    G: ['Grateful', 'Generous', 'Gentle', 'Glorious'],
    H: ['Happy', 'Harmonious', 'Healthy', 'Hopeful'],
    I: ['Inspired', 'Ideal', 'Imaginative', 'Intelligent'],
    J: ['Joyful', 'Jubilant', 'Jolly', 'Jovial'],
    K: ['Kind', 'Keen', 'Kind-hearted', 'Kalon'],
    L: ['Lovely', 'Lively', 'Loving', 'Lucky'],
    M: ['Motivated', 'Majestic', 'Marvelous', 'Merry'],
    N: ['Nice', 'Natural', 'Nifty', 'Nurturing'],
    O: ['Optimistic', 'Outstanding', 'Overjoyed', 'Original'],
    P: ['Proud', 'Peaceful', 'Perfect', 'Playful'],
    Q: ['Quick-witted', 'Quaint', 'Quality', 'Quiet'],
    R: ['Relaxed', 'Radiant', 'Refreshing', 'Rejoicing'],
    S: ['Smiling', 'Stellar', 'Sunny', 'Superb'],
    T: ['Thankful', 'Talented', 'Tenacious', 'Thoughtful'],
    U: ['Upbeat', 'Ultimate', 'Unique', 'Uplifting'],
    V: ['Vibrant', 'Valiant', 'Versatile', 'Victorious'],
    W: ['Wonderful', 'Warm', 'Welcoming', 'Wise'],
    X: ['Xcited', 'Xenial', 'X-factor', 'Xubarant'],
    Y: ['Youthful', 'Yummy', 'Yippee', 'Yearning'],
    Z: ['Zestful', 'Zany', 'Zeal', 'Zippy'],
  },

  Sad: {
    A: ['Alone', 'Abandoned', 'Anguished', 'Aching'],
    B: ['Broken', 'Blue', 'Bereaved', 'Burdened'],
    C: ['Crying', 'Cheerless', 'Cold', 'Crushed'],
    D: ['Depressed', 'Desperate', 'Despondent', 'Dismal'],
    E: ['Empty', 'Elegiac', 'Exiled', 'Exasperated'],
    F: ['Frustrated', 'Forlorn', 'Fragile', 'Frail'],
    G: ['Gloomy', 'Grief-stricken', 'Grim', 'Guilty'],
    H: ['Hopeless', 'Heartbroken', 'Heavy-hearted', 'Hurt'],
    I: ['Isolated', 'Inconsolable', 'Insecure', 'Injured'],
    J: ['Joyless', 'Jilted', 'Jaded', 'Jarred'],
    K: ['Knocked-down', 'Knotty', 'Keening', 'Kicked'],
    L: ['Lonely', 'Low', 'Languishing', 'Lost'],
    M: ['Miserable', 'Melancholy', 'Mournful', 'Moody'],
    N: ['Numb', 'Neglected', 'Nervous', 'Negative'],
    O: ['Overwhelmed', 'Oppressed', 'Obscure', 'Off-balance'],
    P: ['Painful', 'Pessimistic', 'Pitiable', 'Powerless'],
    Q: ['Quiet', 'Quaking', 'Queasy', 'Questioning'],
    R: ['Regretful', 'Rejected', 'Remorseful', 'Resentful'],
    S: ['Sad', 'Sorrowful', 'Somber', 'Spiritless'],
    T: ['Tired', 'Tearful', 'Tragic', 'Troubled'],
    U: ['Unhappy', 'Unloved', 'Upset', 'Useless'],
    V: ['Vulnerable', 'Vague', 'Vanished', 'Vexed'],
    W: ['Weary', 'Wretched', 'Woeful', 'Withdrawn'],
    X: ['Xhausted', 'Xenophobic', 'X-ed out', 'Xasperated'],
    Y: ['Yearning', 'Yielding', 'Yawning', 'Yoked'],
    Z: ['Zoned-out', 'Zeroed', 'Zapped', 'Zigzagged'],
  },

  Angry: {
    A: ['Angry', 'Aggravated', 'Annoyed', 'Acrimonious'],
    B: ['Bitter', 'Ballistic', 'Belligerent', 'Boiling'],
    C: ['Cross', 'Choleric', 'Caustic', 'Churlish'],
    D: ['Disturbed', 'Displeased', 'Defensive', 'Destructive'],
    E: ['Enraged', 'Exasperated', 'Explosive', 'Embittered'],
    F: ['Furious', 'Fuming', 'Fierce', 'Fiery'],
    G: ['Grumpy', 'Galled', 'Grimacing', 'Grit-toothed'],
    H: ['Hostile', 'Hot-headed', 'Hateful', 'Huffy'],
    I: ['Irritated', 'Indignant', 'Irate', 'Irascible'],
    J: ['Jealous', 'Jarring', 'Jovial-less', 'Judgmental'],
    K: ['Keen-tempered', 'Knotty', 'Killing', 'Knuckle-whitening'],
    L: ['Livid', 'Loathing', 'Loud', 'Lashing-out'],
    M: ['Mad', 'Maddened', 'Malicious', 'Menacing'],
    N: ['Nasty', 'Nettled', 'Noisy', 'Negative'],
    O: ['Offended', 'Outraged', 'Obnoxious', 'Oppositional'],
    P: ['Provoked', 'Peeved', 'Perturbed', 'Pissed'],
    Q: ['Quarrelsome', 'Querulous', 'Quaking', 'Quick-tempered'],
    R: ['Raging', 'Resentful', 'Rancorous', 'Riled'],
    S: ['Stressed', 'Seething', 'Savage', 'Sullen'],
    T: ['Tense', 'Ticked-off', 'Turbulent', 'Testy'],
    U: ['Upset', 'Unreasonable', 'Uncontrolled', 'Unpleasant'],
    V: ['Vengeful', 'Violent', 'Vitriolic', 'Vicious'],
    W: ['Wrathful', 'Wild', 'Wicked', 'Wrought-up'],
    X: ['Xtreme', 'Xenophobic', 'Xasperated', 'X-rated'],
    Y: ['Yelling', 'Yammering', 'Yanking', 'Yowling'],
    Z: ['Zapped', 'Zealous', 'Zigzagging', 'Zingy'],
  },

  Neutral: {
    A: ['Apple', 'Airplane', 'Anchor', 'Acorn'],
    B: ['Book', 'Basket', 'Bottle', 'Bridge'],
    C: ['Chair', 'Camera', 'Cloud', 'Coin'],
    D: ['Desk', 'Door', 'Drum', 'Dime'],
    E: ['Envelope', 'Engine', 'Earth', 'Eraser'],
    F: ['Fan', 'Fork', 'Fence', 'Frame'],
    G: ['Glass', 'Guitar', 'Globe', 'Gate'],
    H: ['House', 'Hammer', 'Helmet', 'Hook'],
    I: ['Ink', 'Island', 'Iron', 'Icicle'],
    J: ['Jar', 'Jacket', 'Jet', 'Journal'],
    K: ['Key', 'Kettle', 'Kite', 'Keyboard'],
    L: ['Lamp', 'Ladder', 'Leaf', 'Lock'],
    M: ['Mobile', 'Mirror', 'Magnet', 'Mountain'],
    N: ['Notebook', 'Needle', 'Net', 'Newspaper'],
    O: ['Orange', 'Ocean', 'Oven', 'Oil'],
    P: ['Pen', 'Pencil', 'Plate', 'Phone'],
    Q: ['Queue', 'Quilt', 'Quiver', 'Quartz'],
    R: ['Road', 'Ring', 'Rope', 'Radio'],
    S: ['School', 'Stone', 'Spoon', 'Shirt'],
    T: ['Table', 'Train', 'Ticket', 'Tower'],
    U: ['Umbrella', 'Unit', 'Utensil', 'Urn'],
    V: ['Vehicle', 'Vase', 'Valley', 'Vest'],
    W: ['Window', 'Watch', 'Wall', 'Wheel'],
    X: ['Xylophone', 'X-ray', 'Xebec', 'Xerox'],
    Y: ['Yard', 'Yacht', 'Yarn', 'Yoke'],
    Z: ['Zoo', 'Zipper', 'Zone', 'Zither'],
  },
};